# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'RNPoilabsNavigation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNPoilabsNavigation
	pod 'PoilabsNavigation', '~> 2.6.0'
  pod 'Mapbox-iOS-SDK', '~> 5.9'
  pod 'MapboxMobileEvents'
  
  
end
